#!/usr/bin/env python3

import argparse
import json
from pathlib import Path


SCENARIO_ORDER = [
    "smoke",
    "baseline",
    "cover_fail",
    "accounting_fail",
    "notification_fail",
    "stress",
    "soak",
]


def fmt(value, digits=4):
    if value is None:
        return "N/A"
    return f"{value:.{digits}f}"


def load_report(path: str):
    data = json.loads(Path(path).read_text())
    return data["replicas"], data


def scenario_cell(report: dict, scenario_name: str) -> str:
    scenario = report["scenarios"][scenario_name]
    return "PASS" if scenario["passed"] else "FAIL"


def main() -> None:
    parser = argparse.ArgumentParser(description="Render a replica comparison from multiple test-plan reports.")
    parser.add_argument("reports", nargs="+", help="JSON reports generated by run_test_plan_suite.py")
    parser.add_argument("-o", "--output", default="loadtest/test-plan-suite-comparison.md")
    parser.add_argument("--title", default="FX Trading Test Plan Replica Comparison")
    args = parser.parse_args()

    loaded = sorted(load_report(path) for path in args.reports)
    replicas = [replica for replica, _ in loaded]
    reports = {replica: report for replica, report in loaded}

    lines = [
        f"# {args.title}",
        "",
        "## 判定サマリー",
        "",
        "| シナリオ | " + " | ".join(f"{replicas_i} replicas" for replicas_i in replicas) + " |",
        "|---|" + "|".join("---" for _ in replicas) + "|",
    ]

    for scenario_name in SCENARIO_ORDER:
        description = reports[replicas[0]]["scenarios"][scenario_name]["description"]
        cells = [scenario_cell(reports[replica], scenario_name) for replica in replicas]
        lines.append(f"| {description} (`{scenario_name}`) | " + " | ".join(cells) + " |")

    lines.extend(
        [
            "",
            "## baseline / notification_fail 詳細",
            "",
            "| 指標 | " + " | ".join(f"baseline {replicas_i}r" for replicas_i in replicas) + " |",
            "|---|" + "|".join("---:" for _ in replicas) + "|",
            "| 平均応答(s) | "
            + " | ".join(fmt(reports[replica]["scenarios"]["baseline"]["k6"]["average_s"]) for replica in replicas)
            + " |",
            "| p95(s) | "
            + " | ".join(fmt(reports[replica]["scenarios"]["baseline"]["k6"]["p95_s"]) for replica in replicas)
            + " |",
            "| req/s | "
            + " | ".join(fmt(reports[replica]["scenarios"]["baseline"]["k6"]["requests_per_sec"]) for replica in replicas)
            + " |",
            "| Trace検証数 | "
            + " | ".join(fmt(reports[replica]["scenarios"]["baseline"]["k6"]["trace_sampled"], 0) for replica in replicas)
            + " |",
            "| Trace timeout | "
            + " | ".join(fmt(reports[replica]["scenarios"]["baseline"]["k6"]["trace_timed_out"], 0) for replica in replicas)
            + " |",
            "",
            "| 指標 | " + " | ".join(f"notification_fail {replicas_i}r" for replicas_i in replicas) + " |",
            "|---|" + "|".join("---:" for _ in replicas) + "|",
            "| 平均応答(s) | "
            + " | ".join(fmt(reports[replica]["scenarios"]["notification_fail"]["k6"]["average_s"]) for replica in replicas)
            + " |",
            "| p95(s) | "
            + " | ".join(fmt(reports[replica]["scenarios"]["notification_fail"]["k6"]["p95_s"]) for replica in replicas)
            + " |",
            "| req/s | "
            + " | ".join(fmt(reports[replica]["scenarios"]["notification_fail"]["k6"]["requests_per_sec"]) for replica in replicas)
            + " |",
            "| Trace検証数 | "
            + " | ".join(fmt(reports[replica]["scenarios"]["notification_fail"]["k6"]["trace_sampled"], 0) for replica in replicas)
            + " |",
            "| Trace timeout | "
            + " | ".join(fmt(reports[replica]["scenarios"]["notification_fail"]["k6"]["trace_timed_out"], 0) for replica in replicas)
            + " |",
        ]
    )

    lines.extend(
        [
            "",
            "## 観測ポイント",
            "",
            "- 今回の比較は sampled trace 検証版の同一スイートで揃えています。",
            "- `baseline` と `notification_fail` の PASS/FAIL は、計測系の自己負荷を除去した後の結果です。",
        ]
    )

    Path(args.output).write_text("\n".join(lines) + "\n")
    print(args.output)


if __name__ == "__main__":
    main()
